[project]
name = "mlzoomcamp2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.0",
    "httpx>=0.28.1",
    "jupyter>=1.1.1",
    "mlcroissant>=1.0.22",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
]
